added fakend and created new section Services(SAAS or Commercial)
faker-js/awesome-faker pull request #5
Opened 2024-01-26 08:37 UTC by sanjaykhanssk

2024-01-26 08:38 UTC, ST-DDT commented on README.md
> +- [Fakend - Production Ready Mock API](https://fakend.fyi) - Create mock API for dev and product demos and supercharge your dev team.
```suggestion
## Services (SAAS or Commercial)

- [Fakend - Production Ready Mock API](https://fakend.fyi) - Create mock API for dev and product demos and supercharge your dev team.
```

2024-01-26 13:32 UTC, Shinigami92 approved these changes

2024-01-27 03:21 UTC, sanjaykhanssk reviewed
changes updated

2024-01-27 10:50 UTC, Shinigami92 approved these changes

2024-01-27 11:03 UTC, sanjaykhanssk commented
Hi, what are the next steps? it says its blocked.

![image](https://github.com/faker-js/awesome-faker/assets/29035533/32cdc495-44f6-4e8d-855c-39d46dcd85fd)

2024-01-27 12:55 UTC, matthewmayer commented
> Hi, what are the next steps? it says its blocked.
> 
> ![image](https://private-user-images.githubusercontent.com/29035533/300173571-32cdc495-44f6-4e8d-855c-39d46dcd85fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjAzOTUsIm5iZiI6MTcwNjM2MDA5NSwicGF0aCI6Ii8yOTAzNTUzMy8zMDAxNzM1NzEtMzJjZGM0OTUtNDRmNi00ZThkLTg1NWMtMzlkNDZkY2Q4NWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEyNTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDNmYzVkYTQyNDRlMjJmY2M0MTZkNDdiOWUxZjhmNWExMWI0NzVmNzdjMmEwNzhiMmEzODdkYWNlZjliOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WdSTArb5dFB4V4ECN-DxpL9GD_DCfSyu7Ghj3IDvfSA)

you dont need to do anything else. a maintainer will merge it when approved.

2024-01-27 13:17 UTC, matthewmayer requested changes
As Faker is MIT licensed, I think it would be appropriate to
1. include a courtesy back to fakerjs.dev homepage, and 
2. include a link to the MIT license from your homepage

For example

`Fakend includes code and data from [Faker.js](https://fakerjs.dev) under a [MIT license](https://raw.githubusercontent.com/faker-js/faker/next/LICENSE).`

2024-01-27 15:21 UTC, sanjaykhanssk commented
Defeintly yes, . I am working on the new version of the product(which includes the commercial side ). It will be released next quarter(AMJ). With that, I'm linking and mentioning most of the open-source libraries such as Faker, JSONTree, and couple of other libraries will be linked.

2024-01-28 10:41 UTC, Shinigami92 commented
> As Faker is MIT licensed, I think it would be appropriate to
> 
> 1. include a courtesy link back to fakerjs.dev homepage, and
> 2. include a link to the MIT license from your homepage
> 
> For example
> 
> `Fakend includes code and data from [Faker.js](https://fakerjs.dev) under a [MIT license](https://raw.githubusercontent.com/faker-js/faker/next/LICENSE).`

Beside the fact that I like that suggestion, I would be in favor if you wont block the merge with such a suggestion
Adding the link can be done without immediately requirement of adding us to their credits, even when this is very nice if they would do

2024-01-28 10:53 UTC, matthewmayer approved these changes

2024-01-28 10:54 UTC, matthewmayer commented
ok i accept the promise of @sanjaykhanssk to add the credit soon as sufficient :)

"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

2024-01-28 10:59 UTC, Shinigami92 commented
![image](https://github.com/faker-js/awesome-faker/assets/7195563/8b90f9ae-c345-48dc-8219-0c4ac28dc9b6)

:thinking: 

... I have approved, I am one of the codeowners :thinking: ...
strange

however I will force merge it ^^

2024-01-28 10:59 UTC, merged