chore: organize entries alphabetically and add `interface-forge`
faker-js/awesome-faker pull request #8
Opened 2024-07-06 19:11 UTC by Goldziher

- organize the README.md entries alphabetically
- add the `interface-forge` library

2024-07-06 19:22 UTC, xDivisionByZerox requested changes
Please revert the changes to libraries other that yours. AFAICT the capitalization was correct.

Nevertheless, I'd prefer to not mix separations in a single PR.

2024-07-06 19:22 UTC, xDivisionByZerox commented on README.md
> +- [interface-forge](https://github.com/tool-belt/interface-forge) - A library for mock data generation using factories. This library extends  Faker.js directly.
Duplicated whitespace. Should've propably been catched by static code analysis.

```suggestion
- [interface-forge](https://github.com/tool-belt/interface-forge) - A library for mock data generation using factories. This library extends Faker.js directly.
```

2024-07-07 10:36 UTC, Goldziher commented
> Please revert the changes to libraries other that yours. AFAICT the capitalization was correct.
> 
> Nevertheless, I'd prefer to not mix separations in a single PR.

done

2024-07-07 11:13 UTC, Shinigami92 approved these changes

2024-07-07 11:40 UTC, xDivisionByZerox approved these changes

2024-07-07 11:40 UTC, merged